-- Seed inicial: sistemas, papeis, catalogo de municipios, planos.
-- Idempotente: ON CONFLICT DO NOTHING em tudo, para poder reaplicar.

INSERT INTO plataforma.sistemas (chave, nome) VALUES
    ('tce', 'Plataforma TCE')
ON CONFLICT (chave) DO NOTHING;

-- Papeis do sistema TCE. nivel_plataforma = enxerga alem de uma organizacao.
-- `suporte` NAO e papel: e a flag is_suporte em usuarios_sistema, porque
-- suporte e superadmin tem acessos quase opostos e precisam ser independentes.
INSERT INTO plataforma.papeis (sistema, papel, nome, nivel_plataforma, ordem) VALUES
    ('tce', 'superadmin',       'Superadministrador',         true,  0),
    ('tce', 'admin_escritorio', 'Administrador do escritorio', false, 1),
    ('tce', 'advogado',         'Advogado',                    false, 2),
    ('tce', 'gestor_publico',   'Gestor publico',              false, 3)
ON CONFLICT (sistema, papel) DO NOTHING;

-- Catalogo dos 184 municipios do Ceara. Base compartilhada entre os sistemas
-- deste projeto. Copiado do PortalGov, onde ja estava consolidado.
--
-- ATENCAO: `codigo` aqui e a numeracao do catalogo (Horizonte = '068'), que NAO
-- e o id de localidade da API do TCE (Horizonte = 72). Sao numeracoes
-- diferentes; o vinculo entre elas e feito em tce.municipios.codigo_ibge.
INSERT INTO plataforma.catalogo_municipios (codigo, slug, nome, uf) VALUES
    ('002','abaiara','Abaiara','CE'),
    ('003','acarape','Acarape','CE'),
    ('004','acarau','Acaraú','CE'),
    ('005','acopiara','Acopiara','CE'),
    ('006','aiuaba','Aiuaba','CE'),
    ('007','alcantaras','Alcântaras','CE'),
    ('008','altaneira','Altaneira','CE'),
    ('009','alto-santo','Alto Santo','CE'),
    ('010','amontada','Amontada','CE'),
    ('011','antonina-do-norte','Antonina do Norte','CE'),
    ('012','apuiares','Apuiarés','CE'),
    ('013','aquiraz','Aquiraz','CE'),
    ('014','aracati','Aracati','CE'),
    ('015','aracoiaba','Aracoiaba','CE'),
    ('180','ararenda','Ararendá','CE'),
    ('016','araripe','Araripe','CE'),
    ('017','aratuba','Aratuba','CE'),
    ('018','arneiroz','Arneiroz','CE'),
    ('019','assare','Assaré','CE'),
    ('020','aurora','Aurora','CE'),
    ('021','baixio','Baixio','CE'),
    ('022','banabuiu','Banabuiú','CE'),
    ('023','barbalha','Barbalha','CE'),
    ('024','barreira','Barreira','CE'),
    ('025','barro','Barro','CE'),
    ('026','barroquinha','Barroquinha','CE'),
    ('027','baturite','Baturité','CE'),
    ('028','beberibe','Beberibe','CE'),
    ('029','bela-cruz','Bela Cruz','CE'),
    ('030','boa-viagem','Boa Viagem','CE'),
    ('031','brejo-santo','Brejo Santo','CE'),
    ('032','camocim','Camocim','CE'),
    ('033','campos-sales','Campos Sales','CE'),
    ('034','caninde','Canindé','CE'),
    ('035','capistrano','Capistrano','CE'),
    ('036','caridade','Caridade','CE'),
    ('037','carire','Cariré','CE'),
    ('038','caririacu','Caririaçu','CE'),
    ('039','carius','Cariús','CE'),
    ('040','carnaubal','Carnaubal','CE'),
    ('041','cascavel','Cascavel','CE'),
    ('042','catarina','Catarina','CE'),
    ('181','catunda','Catunda','CE'),
    ('043','caucaia','Caucaia','CE'),
    ('044','cedro','Cedro','CE'),
    ('045','chaval','Chaval','CE'),
    ('182','choro','Choró','CE'),
    ('046','chorozinho','Chorozinho','CE'),
    ('047','coreau','Coreaú','CE'),
    ('048','crateus','Crateús','CE'),
    ('049','crato','Crato','CE'),
    ('050','croata','Croatá','CE'),
    ('051','cruz','Cruz','CE'),
    ('052','deputado-irapuan-pinheiro','Deputado Irapuan Pinheiro','CE'),
    ('053','erere','Ererê','CE'),
    ('054','eusebio','Eusébio','CE'),
    ('055','farias-brito','Farias Brito','CE'),
    ('056','forquilha','Forquilha','CE'),
    ('057','fortaleza','Fortaleza','CE'),
    ('183','fortim','Fortim','CE'),
    ('058','frecheirinha','Frecheirinha','CE'),
    ('059','general-sampaio','General Sampaio','CE'),
    ('060','graca','Graça','CE'),
    ('061','granja','Granja','CE'),
    ('062','granjeiro','Granjeiro','CE'),
    ('063','groairas','Groaíras','CE'),
    ('064','guaiuba','Guaiúba','CE'),
    ('065','guaraciaba-do-norte','Guaraciaba do Norte','CE'),
    ('066','guaramiranga','Guaramiranga','CE'),
    ('067','hidrolandia','Hidrolândia','CE'),
    ('068','horizonte','Horizonte','CE'),
    ('069','ibaretama','Ibaretama','CE'),
    ('070','ibiapina','Ibiapina','CE'),
    ('071','ibicuitinga','Ibicuitinga','CE'),
    ('072','icapui','Icapuí','CE'),
    ('073','ico','Icó','CE'),
    ('074','iguatu','Iguatu','CE'),
    ('075','independencia','Independência','CE'),
    ('076','ipaporanga','Ipaporanga','CE'),
    ('077','ipaumirim','Ipaumirim','CE'),
    ('078','ipu','Ipu','CE'),
    ('079','ipueiras','Ipueiras','CE'),
    ('080','iracema','Iracema','CE'),
    ('081','iraucuba','Irauçuba','CE'),
    ('082','itaicaba','Itaiçaba','CE'),
    ('184','itaitinga','Itaitinga','CE'),
    ('083','itapaje','Itapajé','CE'),
    ('084','itapipoca','Itapipoca','CE'),
    ('085','itapiuna','Itapiúna','CE'),
    ('086','itarema','Itarema','CE'),
    ('087','itatira','Itatira','CE'),
    ('088','jaguaretama','Jaguaretama','CE'),
    ('089','jaguaribara','Jaguaribara','CE'),
    ('090','jaguaribe','Jaguaribe','CE'),
    ('091','jaguaruana','Jaguaruana','CE'),
    ('092','jardim','Jardim','CE'),
    ('093','jati','Jati','CE'),
    ('185','jijoca-de-jericoacoara','Jijoca de Jericoacoara','CE'),
    ('094','juazeiro-do-norte','Juazeiro do Norte','CE'),
    ('095','jucas','Jucás','CE'),
    ('096','lavras-da-mangabeira','Lavras da Mangabeira','CE'),
    ('097','limoeiro-do-norte','Limoeiro do Norte','CE'),
    ('098','madalena','Madalena','CE'),
    ('099','maracanau','Maracanaú','CE'),
    ('100','maranguape','Maranguape','CE'),
    ('101','marco','Marco','CE'),
    ('102','martinopole','Martinópole','CE'),
    ('103','massape','Massapê','CE'),
    ('104','mauriti','Mauriti','CE'),
    ('105','meruoca','Meruoca','CE'),
    ('106','milagres','Milagres','CE'),
    ('107','milha','Milhã','CE'),
    ('108','miraima','Miraima','CE'),
    ('109','missao-velha','Missão Velha','CE'),
    ('111','mombaca','Mombaça','CE'),
    ('112','monsenhor-tabosa','Monsenhor Tabosa','CE'),
    ('113','morada-nova','Morada Nova','CE'),
    ('114','moraujo','Moraújo','CE'),
    ('115','morrinhos','Morrinhos','CE'),
    ('110','mucambo','Mucambo','CE'),
    ('116','mulungu','Mulungu','CE'),
    ('117','nova-olinda','Nova Olinda','CE'),
    ('118','nova-russas','Nova Russas','CE'),
    ('119','novo-oriente','Novo Oriente','CE'),
    ('120','ocara','Ocara','CE'),
    ('121','oros','Orós','CE'),
    ('122','pacajus','Pacajus','CE'),
    ('123','pacatuba','Pacatuba','CE'),
    ('124','pacoti','Pacoti','CE'),
    ('125','pacuja','Pacujá','CE'),
    ('126','palhano','Palhano','CE'),
    ('127','palmacia','Palmácia','CE'),
    ('128','paracuru','Paracuru','CE'),
    ('129','paraipaba','Paraipaba','CE'),
    ('130','parambu','Parambu','CE'),
    ('131','paramoti','Paramoti','CE'),
    ('132','pedra-branca','Pedra Branca','CE'),
    ('133','penaforte','Penaforte','CE'),
    ('134','pentecoste','Pentecoste','CE'),
    ('135','pereiro','Pereiro','CE'),
    ('136','pindoretama','Pindoretama','CE'),
    ('137','piquet-carneiro','Piquet Carneiro','CE'),
    ('138','pires-ferreira','Pires Ferreira','CE'),
    ('139','poranga','Poranga','CE'),
    ('140','porteiras','Porteiras','CE'),
    ('141','potengi','Potengi','CE'),
    ('142','potiretama','Potiretama','CE'),
    ('143','quiterianopolis','Quiterianópolis','CE'),
    ('144','quixada','Quixadá','CE'),
    ('145','quixelo','Quixelô','CE'),
    ('146','quixeramobim','Quixeramobim','CE'),
    ('147','quixere','Quixeré','CE'),
    ('148','redencao','Redenção','CE'),
    ('149','reriutaba','Reriutaba','CE'),
    ('150','russas','Russas','CE'),
    ('151','saboeiro','Saboeiro','CE'),
    ('152','salitre','Salitre','CE'),
    ('155','santa-quiteria','Santa Quitéria','CE'),
    ('153','santana-do-acarau','Santana do Acaraú','CE'),
    ('154','santana-do-cariri','Santana do Cariri','CE'),
    ('156','sao-benedito','São Benedito','CE'),
    ('157','sao-goncalo-do-amarante','São Gonçalo do Amarante','CE'),
    ('158','sao-joao-do-jaguaribe','São João do Jaguaribe','CE'),
    ('159','sao-luis-do-curu','São Luís do Curu','CE'),
    ('160','senador-pompeu','Senador Pompeu','CE'),
    ('161','senador-sa','Senador Sá','CE'),
    ('162','sobral','Sobral','CE'),
    ('163','solonopole','Solonópole','CE'),
    ('164','tabuleiro-do-norte','Tabuleiro do Norte','CE'),
    ('165','tamboril','Tamboril','CE'),
    ('166','tarrafas','Tarrafas','CE'),
    ('167','taua','Tauá','CE'),
    ('168','tejucuoca','Tejucuoca','CE'),
    ('169','tiangua','Tianguá','CE'),
    ('170','trairi','Trairi','CE'),
    ('171','tururu','Tururu','CE'),
    ('172','ubajara','Ubajara','CE'),
    ('173','umari','Umari','CE'),
    ('174','umirim','Umirim','CE'),
    ('175','uruburetama','Uruburetama','CE'),
    ('176','uruoca','Uruoca','CE'),
    ('177','varjota','Varjota','CE'),
    ('178','varzea-alegre','Várzea Alegre','CE'),
    ('179','vicosa-do-ceara','Viçosa do Ceará','CE')
ON CONFLICT (codigo) DO NOTHING;

-- Municipios na numeracao da API do TCE. So Horizonte ativo no piloto; os
-- demais entram conforme o console interno for ativando. A Fase 2 popula o
-- resto a partir da tabela auxiliar `localidade` da API.
INSERT INTO tce.municipios (id, descricao, codigo_ibge, ativo) VALUES
    (72, 'HORIZONTE', '068', true)
ON CONFLICT (id) DO NOTHING;

-- Planos. Valores a validar comercialmente: sao configuracao, nao codigo.
-- Municipios monitorados sao ilimitados em todos - nao ha coluna de limite.
INSERT INTO tce.planos
    (slug, nome, ordem, preco_mensal, preco_anual,
     limite_processos_monitorados, limite_usuarios, limite_armazenamento_mb,
     limite_notificacoes_wpp_mes, limite_quadros, limite_creditos_ia_mes)
VALUES
    ('gratuito',        'Gratuito',         0,    0.00,     0.00,     5,  1,   100,    0,  1,  0),
    ('gestor',          'Gestor',           1,  129.00,  1290.00,    25,  2,  1024,  100,  2,  5),
    ('escritorio',      'Escritorio',       2,  449.00,  4490.00,   300,  5, 10240, 1000,  4, 20),
    ('escritorio-plus', 'Escritorio Plus',  3, 1049.00, 10490.00,  1000, 15, 30720, 5000, 10, 50)
ON CONFLICT (slug) DO NOTHING;
